### ISSUE TITLE
Merging audio and video fails with exit status 1 for some videos.

### ISSUE THREAD

**Issue by apatheticposture** [Solirs/gettit#2]
$  gettit -u https://www.reddit.com/r/aww/comments/rxtjyl/whenever_i_do_the_dishes_shark_will_circle_my/ -o kittycat2.mp4
[+] Initializing...

[+] Fetching url of the source video file...

[+] Downloading source video file...
[####################]100% 27 MB/27 MB
[+] Downloading audio...
[####################]100% 243 B/243 B
[+] Merging audio and video...
2022/01/07 01:55:16 exit status 1

This results in two temporary files:

-rw-r--r--   1 posture restricted   27311812 Jan  7 01:55  esKhncWTij.mp4
-rw-r--r--   1 posture restricted        243 Jan  7 01:55  lgwiWXMSNP.mp4

**Comment by Solirs** [comment]
I tried to reproduce the issue but it wasn't fruitful, file downloaded just fine, the video seems to not have any audio, (even the original post on reddit), maybe it could be what's causing the issue ? I'm going to push a feature to skip downloading audio (i was planning to anyways) to maybe mitigate the issue and dig deeper into it, can you try to merge those manually using `ffmpeg -i video.mp4 -i audio.mp4 -c:v copy -c:a aac output.mp4` and send the output ? Maybe we'll find out whats wrong with it...

**Comment by Solirs** [comment]
This issue is almost a year old at this point. Im going to consider it dead and close it. Feel free to reopen it.

**Comment by ThothLogos** [comment]
I found this happens when the requested output file already exists, it doesn't overwrite, it exits 1 and doesn't have time to perform the cleanup of the pre-merge a/v stream files

**Comment by Solirs** [comment]
Good to know, i'll fix that.

**Comment by Solirs** [comment]
Fixed in latest commits
